# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-08-19 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='name',
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default=None, help_text='正文必须时MarkDown格式', verbose_name='正文'),
        ),
        migrations.AddField(
            model_name='post',
            name='desc',
            field=models.CharField(blank=True, max_length=1024, verbose_name='摘要'),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default=2, max_length=255, verbose_name='标题'),
            preserve_default=False,
        ),
    ]
