# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-08-19 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20230819_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='正文必须时MarkDown格式', verbose_name='正文'),
        ),
    ]
